#!/bin/bash

# Färger
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
RESET='\033[0m'

# Funktion för att rensa skärmen och skriva header
print_header() {
    clear
    echo -e "${CYAN}╔════════════════════════════════════════════════╗${RESET}"
    echo -e "${CYAN}║${WHITE}      Clementinose Terminal Menu v1.2        ${CYAN}║${RESET}"
    echo -e "${CYAN}╚════════════════════════════════════════════════╝${RESET}"
    echo ""
}

# Funktion för att köra externa skript
run_script() {
    echo -e "${BLUE}▶ Running $1...${RESET}"
    bash <(curl -fsSL "$2") "$PUBKEY"
    echo ""
    read -p "Press Enter to return to menu..."
}

# Funktion för systeminfo
system_info() {
    echo -e "${MAGENTA}🖥️ System Information${RESET}"
    echo "==============================="
    echo "Hostname: $(hostname)"
    echo "IP: $(hostname -I | awk '{print $1}')"
    echo "Uptime: $(uptime -p)"
    echo "CPU: $(lscpu | grep 'Model name' | awk -F: '{print $2}' | xargs)"
    echo "RAM: $(free -h | awk '/Mem:/ {print $2 " total, " $3 " used"}')"
    echo "Disk: $(df -h / | awk 'NR==2 {print $2 " total, " $3 " used"}')"
    echo "==============================="
    read -p "Press Enter to return to menu..."
}

# Funktion för att sätta lösenord för användare
set_user_password() {
    read -p "Enter new password for user 'clements': " -s NEWPASS
    echo ""
    read -p "Confirm password: " -s CONFIRMPASS
    echo ""
    if [ "$NEWPASS" == "$CONFIRMPASS" ]; then
        echo "clements:$NEWPASS" | sudo chpasswd
        echo -e "${GREEN}✅ Password updated successfully!${RESET}"
    else
        echo -e "${RED}❌ Passwords do not match.${RESET}"
    fi
    read -p "Press Enter to return to menu..."
}

# Lägg in din publika SSH-nyckel
PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINr2Lm9pY8GLLgaPvmD+kbNKsQdJuKdHfa6amveI4xFL Generated By Termius"

while true; do
    print_header

    # Menyalternativ
    echo -e "${GREEN}1)${RESET} LXC SSH setup"
    echo -e "${GREEN}2)${RESET} Proxmox SSH setup"
    echo -e "${GREEN}3)${RESET} Node Power Monitor"
    echo -e "${GREEN}4)${RESET} Node Temperature Monitor"
    echo -e "${GREEN}5)${RESET} Node Fan Monitor"
    echo -e "${GREEN}6)${RESET} Node Network Monitor"
    echo -e "${GREEN}7)${RESET} System Info"
    echo -e "${GREEN}8)${RESET} Set user password"
    echo -e "${RED}9)${RESET} Exit"
    echo ""

    read -p "$(echo -e ${YELLOW}Select an option: ${RESET})" choice

    case "$choice" in
        1) run_script "LXC SSH setup" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/cool-menu-ui/lxc-ssh/init.sh" ;;
        2) run_script "Proxmox SSH setup" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/cool-menu-ui/proxmox-ssh/init-proxmox.sh" ;;
        3) run_script "Node Power Monitor" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/cool-menu-ui/power-monitor/monitor.sh" ;;
        4) run_script "Node Temperature Monitor" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/cool-menu-ui/temp-monitor/temp.sh" ;;
        5) run_script "Node Fan Monitor" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/cool-menu-ui/fan-monitor/fans.sh" ;;
        6) run_script "Node Network Monitor" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/cool-menu-ui/network-monitor/network.sh" ;;
        7) system_info ;;
        8) set_user_password ;;
        9) echo -e "${RED}👋 Goodbye${RESET}"; exit 0 ;;
        *) echo -e "${RED}❌ Invalid choice${RESET}"; read -p "Press Enter to return to menu..." ;;
    esac
done
