#!/bin/bash

clear
echo "==============================="
echo " Clementinose Terminal Menu"
echo "==============================="
echo ""
echo "1) LXC SSH setup"
echo "2) Proxmox SSH setup"
echo "3) Node Power Monitor"
echo "4) Node Temperature Monitor"
echo "5) Node Fan Monitor"
echo "6) Node Network Monitor"
echo "7) Exit"
echo ""

read -p "Välj ett alternativ: " choice

PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINr2Lm9pY8GLLgaPvmD+kbNKsQdJuKdHfa6amveI4xFL Generated By Termius"

case "$choice" in
  1)
    echo "▶ Kör LXC SSH setup..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/lxc-ssh/init.sh) "$PUBKEY"
    ;;
  2)
    echo "▶ Kör Proxmox SSH setup..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/proxmox-ssh/init-proxmox.sh) "$PUBKEY"
    ;;
  3)
    echo "▶ Kör Node Power Monitor..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/power-monitor/monitor.sh)
    ;;
  4)
    echo "▶ Kör Node Temperature Monitor..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/temp-monitor/temp.sh)
    ;;
  5)
    echo "▶ Kör Node Fan Monitor..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/fan-monitor/fans.sh)
    ;;
  6)
    echo "▶ Kör Node Network Monitor..."
    bash <(curl -fsSL https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/network-monitor/network.sh)
    ;;
  7)
    echo "👋 Hej då"
    exit 0
    ;;
  *)
    echo "❌ Fel val"
    ;;
esac
