#!/bin/bash

# Färger
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
RESET='\033[0m'

# Clear screen
clear

# Banner Clements Inc.
echo -e "${CYAN}"
echo "   _____   _                                     _                 _                    "
echo "  / ____| | |                                   | |               (_)                   "
echo " | |      | |   ___   _ __ ___     ___   _ __   | |_   ___         _   _ __     ___     "
echo " | |      | |  / _ \ | '_ \` _ \   / _ \ | '_ \  | __| / __|       | | | '_ \   / __|    "
echo " | |____  | | |  __/ | | | | | | |  __/ | | | | | |_  \__ \       | | | | | | | (__   _ "
echo "  \_____| |_|  \___| |_| |_| |_| \___| |_| |_|  \__| |___/       |_| |_| |_|  \___| (_)"
echo -e "${RESET}"
echo ""

# Menyalternativ
echo -e "${GREEN}1)${RESET} LXC SSH setup"
echo -e "${GREEN}2)${RESET} Proxmox SSH setup (clements)"
echo -e "${GREEN}3)${RESET} Proxmox SSH setup (root)"
echo -e "${GREEN}4)${RESET} Node Power Monitor"
echo -e "${GREEN}5)${RESET} Node Temperature Monitor"
echo -e "${GREEN}6)${RESET} Node Fan Monitor"
echo -e "${GREEN}7)${RESET} Node Network Monitor"
echo -e "${GREEN}8)${RESET} Node System Monitor"
echo -e "${RED}9)${RESET} Exit"
echo ""

# Läs användarval
read -p "$(echo -e ${YELLOW}Välj ett alternativ: ${RESET})" choice

PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINr2Lm9pY8GLLgaPvmD+kbNKsQdJuKdHfa6amveI4xFL Generated By Termius"

# Funktion för att köra skript via URL
run_script() {
    echo -e "${BLUE}▶ Kör $1...${RESET}"
    bash <(curl -fsSL "$2") "$PUBKEY"
    echo ""
    read -p "Tryck Enter för att återgå till menyn..."
}

# Kör användarval
case "$choice" in
  1) run_script "LXC SSH setup" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/lxc-ssh/init.sh" ;;
  2) run_script "Proxmox SSH setup (clements)" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/proxmox-ssh/init-proxmox.sh" ;;
  3) run_script "Proxmox SSH setup (root)" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/proxmox-ssh/init-proxmox-root.sh" ;;
  4) run_script "Node Power Monitor" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/power-monitor/monitor.sh" ;;
  5) run_script "Node Temperature Monitor" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/temp-monitor/temp.sh" ;;
  6) run_script "Node Fan Monitor" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/fan-monitor/fans.sh" ;;
  7) run_script "Node Network Monitor" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/network-monitor/network.sh" ;;
  8) run_script "Node System Monitor" "https://raw.githubusercontent.com/Clementinose/proxmox-utils/main/system-monitor/system.sh" ;;
  9) echo -e "${RED}👋 Hej då${RESET}" ; exit 0 ;;
  *) echo -e "${RED}❌ Fel val${RESET}" ;;
esac
