#!/bin/bash
set -e

# Namn på användaren som ska skapas
USERNAME="clements"

# Kontrollera att public key skickas med som argument
if [ -z "$1" ]; then
  echo "❌ Ingen SSH public key angiven"
  echo "Usage: ./init.sh \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINr2Lm9pY8GLLgaPvmD+kbNKsQdJuKdHfa6amveI4xFL Generated By Termius\""
  exit 1
fi

PUBKEY="$1"

# Installera SSH-server och sudo om det inte finns
apt update
apt install -y openssh-server sudo

# Skapa användare och lägg till i sudo-gruppen
useradd -m -s /bin/bash "$USERNAME" 2>/dev/null || true
usermod -aG sudo "$USERNAME"

# Skapa .ssh-mapp och authorized_keys
mkdir -p /home/$USERNAME/.ssh
chmod 700 /home/$USERNAME/.ssh
echo "$PUBKEY" > /home/$USERNAME/.ssh/authorized_keys
chmod 600 /home/$USERNAME/.ssh/authorized_keys
chown -R $USERNAME:$USERNAME /home/$USERNAME/.ssh

# Stäng lösenordsinloggning och root-login
sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin no/' /etc/ssh/sshd_config

# Starta om SSH
systemctl enable ssh
systemctl restart ssh

echo "✅ Klar: $USERNAME är admin + SSH-nyckel"
